Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,10 +3,10 @@ name: CI/CD Pipeline for NestJS
 on:
   push:
     branches:
-      - master  # Pipeline akan berjalan saat ada push ke branch "main"
+      - master  # Pipeline akan berjalan saat ada push ke branch "master"
   pull_request:
     branches:
-      - master  # Pipeline juga akan berjalan pada pull request ke branch "main"
+      - master  # Pipeline juga akan berjalan pada pull request ke branch "master"
 
 jobs:
   build-and-deploy:
@@ -21,7 +21,7 @@ jobs:
       - name: Set up Node.js 20
         uses: actions/setup-node@v3
         with:
-          node-version: '20'  # Menggunakan Node.js versi 20
+          node-version: '20'
 
       # Step 3: Cache Node.js modules untuk mempercepat proses instalasi dependensi
       - name: Cache Node.js modules
@@ -32,10 +32,11 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
 
-      # Step 4: Install dependencies
+      # Step 4: Install dependencies dengan fallback ke npm install
       - name: Install dependencies
         run: |
-          npm ci  # Menggunakan npm ci untuk instalasi yang lebih cepat dari package-lock.json
+          echo "Running npm ci..."
+          npm ci || (echo "npm ci failed, falling back to npm install..." && npm install)
 
       # Step 5: Build project
       - name: Build the project
